### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jglidden**
Refactors code for lasso, ridge and least squares. Needs a lot more validation. Results from three methods are suspiciously similar:

```
[1] "Ridge MSE: 0.227498078255714 0.000135204365637957"
[1] "Lasso MSE:  0.22901175744563 ,  0.00019134237926112"
[1] "Least Squares MSE:  0.2280341661959 ,  0.000296507786763245"
```

### CODE REVIEW

**Comment by jglidden** [comment]
Okay, by looking at the coefficients I at least convinced myself that it is doing the regularization. I'll write some automatic tests for things like that in the next update.

**Comment by jglidden** [comment]
```
# Sum of coefficients for each fold
# Ridge:
[1] 15.14476
[1] 14.95835
[1] 15.42463
[1] 15.20153
[1] 15.35271
[1] 15.20671
[1] 15.11062
[1] 16.33432
[1] 15.06867
[1] 14.31629
# Lasso
[1] 14.26327
[1] 14.1926
[1] 14.408
[1] 14.37322
[1] 14.41007
[1] 14.24788
[1] 14.25792
[1] 14.81631
[1] 14.30507
[1] 13.43114
# Least squares
[1] 15.31214
[1] 14.35677
[1] 15.64579
[1] 14.8708
[1] 15.00696
[1] 15.12939
[1] 15.03414
[1] 16.5969
[1] 15.20966
[1] 13.76123
```

**Comment by JackJWillis** [comment]
Thanks, looks good. What's the %>% in lasso_predict? Amazing how much shorter that code could be. Note for a number of the other models we won't want data in model matrix form (we also might want to do grouped lasso, passing first the data in standard form), so we will need to have alternative create data functions eventually. Good to pull

**Comment by jglidden** [comment]
%>% is pipe from the magrittr library:
- http://blog.revolutionanalytics.com/2014/07/magrittr-simplifying-r-code-with-pipes.html
- https://github.com/smbache/magrittr

**Comment by jglidden** [comment]
FYI, you can comment directly on lines of code under the files changed tab.

**Pull request merged**
